export const NATIONALITIES: { code3: string; code2: string; name: string }[] = [
  { code3: 'AFG', code2: 'af', name: 'Afeganistão' },
  { code3: 'AFS', code2: 'za', name: 'África do Sul' },
  { code3: 'ALB', code2: 'al', name: 'Albânia' },
  { code3: 'GER', code2: 'de', name: 'Alemanha' },
  { code3: 'AND', code2: 'ad', name: 'Andorra' },
  { code3: 'ANG', code2: 'ao', name: 'Angola' },
  { code3: 'ANT', code2: 'ag', name: 'Antígua e Barbuda' },
  { code3: 'SAU', code2: 'sa', name: 'Arábia Saudita' },
  { code3: 'ALG', code2: 'dz', name: 'Argélia' },
  { code3: 'ARG', code2: 'ar', name: 'Argentina' },
  { code3: 'ARM', code2: 'am', name: 'Armênia' },
  { code3: 'AUS', code2: 'au', name: 'Austrália' },
  { code3: 'AUT', code2: 'at', name: 'Áustria' },
  { code3: 'AZE', code2: 'az', name: 'Azerbaijão' },
  { code3: 'BAH', code2: 'bh', name: 'Bahrein' },
  { code3: 'BGD', code2: 'bd', name: 'Bangladesh' },
  { code3: 'BAR', code2: 'bb', name: 'Barbados' },
  { code3: 'BLR', code2: 'by', name: 'Bielorrússia' },
  { code3: 'BEL', code2: 'be', name: 'Bélgica' },
  { code3: 'BEN', code2: 'bj', name: 'Benin' },
  { code3: 'BOL', code2: 'bo', name: 'Bolívia' },
  { code3: 'BIH', code2: 'ba', name: 'Bósnia' },
  { code3: 'BSW', code2: 'bw', name: 'Botsuana' },
  { code3: 'BRA', code2: 'br', name: 'Brasil' },
  { code3: 'BGR', code2: 'bg', name: 'Bulgária' },
  { code3: 'BFA', code2: 'bf', name: 'Burkina Faso' },
  { code3: 'CDV', code2: 'cv', name: 'Cabo Verde' },
  { code3: 'CAM', code2: 'cm', name: 'Camarões' },
  { code3: 'CAN', code2: 'ca', name: 'Canadá' },
  { code3: 'QAT', code2: 'qa', name: 'Catar' },
  { code3: 'KAZ', code2: 'kz', name: 'Cazaquistão' },
  { code3: 'CHL', code2: 'cl', name: 'Chile' },
  { code3: 'CHN', code2: 'cn', name: 'China' },
  { code3: 'CYP', code2: 'cy', name: 'Chipre' },
  { code3: 'COL', code2: 'co', name: 'Colômbia' },
  { code3: 'CON', code2: 'cg', name: 'Congo' },
  { code3: 'KOR', code2: 'kr', name: 'Coreia do Sul' },
  { code3: 'CIV', code2: 'ci', name: 'Costa do Marfim' },
  { code3: 'CRC', code2: 'cr', name: 'Costa Rica' },
  { code3: 'HRV', code2: 'hr', name: 'Croácia' },
  { code3: 'CUB', code2: 'cu', name: 'Cuba' },
  { code3: 'DNK', code2: 'dk', name: 'Dinamarca' },
  { code3: 'DOM', code2: 'do', name: 'República Dominicana' },
  { code3: 'EGY', code2: 'eg', name: 'Egito' },
  { code3: 'ELS', code2: 'sv', name: 'El Salvador' },
  { code3: 'ARE', code2: 'ae', name: 'Emirados Árabes' },
  { code3: 'EQU', code2: 'ec', name: 'Equador' },
  { code3: 'SCO', code2: 'gb-sct', name: 'Escócia' },
  { code3: 'SVK', code2: 'sk', name: 'Eslováquia' },
  { code3: 'SVN', code2: 'si', name: 'Eslovênia' },
  { code3: 'ESP', code2: 'es', name: 'Espanha' },
  { code3: 'USA', code2: 'us', name: 'Estados Unidos' },
  { code3: 'EST', code2: 'ee', name: 'Estônia' },
  { code3: 'FIN', code2: 'fi', name: 'Finlândia' },
  { code3: 'FRA', code2: 'fr', name: 'França' },
  { code3: 'GAB', code2: 'ga', name: 'Gabão' },
  { code3: 'GAM', code2: 'gm', name: 'Gâmbia' },
  { code3: 'GAN', code2: 'gh', name: 'Gana' },
  { code3: 'GEO', code2: 'ge', name: 'Geórgia' },
  { code3: 'GRE', code2: 'gr', name: 'Grécia' },
  { code3: 'GUA', code2: 'gt', name: 'Guatemala' },
  { code3: 'GUI', code2: 'gn', name: 'Guiné' },
  { code3: 'GEQ', code2: 'gq', name: 'Guiné Equatorial' },
  { code3: 'HAI', code2: 'ht', name: 'Haiti' },
  { code3: 'NED', code2: 'nl', name: 'Holanda' },
  { code3: 'HON', code2: 'hn', name: 'Honduras' },
  { code3: 'HUN', code2: 'hu', name: 'Hungria' },
  { code3: 'IND', code2: 'in', name: 'Índia' },
  { code3: 'ENG', code2: 'gb-eng', name: 'Inglaterra' },
  { code3: 'IRN', code2: 'ir', name: 'Irã' },
  { code3: 'IRQ', code2: 'iq', name: 'Iraque' },
  { code3: 'IRL', code2: 'ie', name: 'Irlanda' },
  { code3: 'NIR', code2: 'gb-nir', name: 'Irlanda do Norte' },
  { code3: 'ISL', code2: 'is', name: 'Islândia' },
  { code3: 'ISR', code2: 'il', name: 'Israel' },
  { code3: 'ITA', code2: 'it', name: 'Itália' },
  { code3: 'JAM', code2: 'jm', name: 'Jamaica' },
  { code3: 'JPN', code2: 'jp', name: 'Japão' },
  { code3: 'JOR', code2: 'jo', name: 'Jordânia' },
  { code3: 'KOS', code2: 'xk', name: 'Kosovo' },
  { code3: 'LVA', code2: 'lv', name: 'Letônia' },
  { code3: 'LBN', code2: 'lb', name: 'Líbano' },
  { code3: 'LTU', code2: 'lt', name: 'Lituânia' },
  { code3: 'MKD', code2: 'mk', name: 'Macedônia do Norte' },
  { code3: 'MAD', code2: 'mg', name: 'Madagascar' },
  { code3: 'MAL', code2: 'ml', name: 'Mali' },
  { code3: 'MAR', code2: 'ma', name: 'Marrocos' },
  { code3: 'MRT', code2: 'mr', name: 'Mauritânia' },
  { code3: 'MEX', code2: 'mx', name: 'México' },
  { code3: 'MDA', code2: 'md', name: 'Moldávia' },
  { code3: 'MNE', code2: 'me', name: 'Montenegro' },
  { code3: 'MOZ', code2: 'mz', name: 'Moçambique' },
  { code3: 'NAM', code2: 'na', name: 'Namíbia' },
  { code3: 'NIC', code2: 'ni', name: 'Nicarágua' },
  { code3: 'NIG', code2: 'ng', name: 'Nigéria' },
  { code3: 'NOR', code2: 'no', name: 'Noruega' },
  { code3: 'NZL', code2: 'nz', name: 'Nova Zelândia' },
  { code3: 'OMN', code2: 'om', name: 'Omã' },
  { code3: 'WAL', code2: 'gb-wls', name: 'País de Gales' },
  { code3: 'PAN', code2: 'pa', name: 'Panamá' },
  { code3: 'PAR', code2: 'py', name: 'Paraguai' },
  { code3: 'PER', code2: 'pe', name: 'Peru' },
  { code3: 'POL', code2: 'pl', name: 'Polônia' },
  { code3: 'POR', code2: 'pt', name: 'Portugal' },
  { code3: 'KEN', code2: 'ke', name: 'Quênia' },
  { code3: 'KGZ', code2: 'kg', name: 'Quirguistão' },
  { code3: 'RDC', code2: 'cd', name: 'RD Congo' },
  { code3: 'CZE', code2: 'cz', name: 'República Tcheca' },
  { code3: 'ROU', code2: 'ro', name: 'Romênia' },
  { code3: 'RUS', code2: 'ru', name: 'Rússia' },
  { code3: 'SEN', code2: 'sn', name: 'Senegal' },
  { code3: 'SRB', code2: 'rs', name: 'Sérvia' },
  { code3: 'SUD', code2: 'sd', name: 'Sudão' },
  { code3: 'SUI', code2: 'ch', name: 'Suíça' },
  { code3: 'SWE', code2: 'se', name: 'Suécia' },
  { code3: 'SYR', code2: 'sy', name: 'Síria' },
  { code3: 'TAZ', code2: 'tz', name: 'Tanzânia' },
  { code3: 'THA', code2: 'th', name: 'Tailândia' },
  { code3: 'TOG', code2: 'tg', name: 'Togo' },
  { code3: 'TRI', code2: 'tt', name: 'Trindade e Tobago' },
  { code3: 'TUN', code2: 'tn', name: 'Tunísia' },
  { code3: 'TUR', code2: 'tr', name: 'Turquia' },
  { code3: 'UKR', code2: 'ua', name: 'Ucrânia' },
  { code3: 'UGA', code2: 'ug', name: 'Uganda' },
  { code3: 'URU', code2: 'uy', name: 'Uruguai' },
  { code3: 'UZB', code2: 'uz', name: 'Uzbequistão' },
  { code3: 'VEN', code2: 've', name: 'Venezuela' },
  { code3: 'VNM', code2: 'vn', name: 'Vietnã' },
  { code3: 'ZAM', code2: 'zm', name: 'Zâmbia' },
  { code3: 'COM', code2: 'km', name: 'Comores' },
  { code3: 'NGR', code2: 'ne', name: 'Niger' },
  { code3: 'LBY', code2: 'LY', name: 'Líbia' },
  { code3: 'ERI', code2: 'ER', name: 'Eritreia' },
  { code3: 'SLE', code2: 'SL', name: 'Serra Leoa' },
  { code3: 'MWI', code2: 'MW', name: 'Malawi' },
  { code3: 'ZIM', code2: 'ZW', name: 'Zimbábue' },
  { code3: 'RWA', code2: 'RW', name: 'Ruanda' },
  { code3: 'GNB', code2: 'GW', name: 'Guiné-Bissau' },
  { code3: 'CTA', code2: 'CF', name: 'República Centro-Africana' },
  { code3: 'LBR', code2: 'LR', name: 'Libéria' },
  { code3: 'LES', code2: 'LS', name: 'Lesoto' },
  { code3: 'BDI', code2: 'BI', name: 'Burundi' },
  { code3: 'ETH', code2: 'ET', name: 'Etiópia' },
  { code3: 'SSD', code2: 'SS', name: 'Sudão do Sul' },
  { code3: 'CHA', code2: 'TD', name: 'Chade' },
  { code3: 'MRI', code2: 'MU', name: 'Ilhas Maurício' },
  { code3: 'SWZ', code2: 'SZ', name: 'Eswatini' },
  { code3: 'STP', code2: 'ST', name: 'São Tomé e Príncipe' },
  { code3: 'DJI', code2: 'DJ', name: 'Djibuti' },
  { code3: 'SOM', code2: 'SO', name: 'Somália' },
  { code3: 'SEY', code2: 'SC', name: 'Seicheles' },
  { code3: 'LUX', code2: 'LU', name: 'Luxemburgo' },
  { code3: 'FRO', code2: 'FO', name: 'Ilhas Faroe' },
  { code3: 'MLT', code2: 'MT', name: 'Malta' },
  { code3: 'GIB', code2: 'GI', name: 'Gibraltar' },
  { code3: 'LIE', code2: 'LI', name: 'Liechtenstein' },
  { code3: 'SMR', code2: 'SM', name: 'San Marino' },
  { code3: 'MON', code2: 'MC', name: 'Mônaco' },
  { code3: 'CUR', code2: 'CW', name: 'Curaçao' },
  { code3: 'SUR', code2: 'SR', name: 'Suriname' },
  { code3: 'GNA', code2: 'GY', name: 'Guiana' },
  { code3: 'SCN', code2: 'KN', name: 'São Cristóvão e Neves' },
  { code3: 'PRC', code2: 'PR', name: 'Porto Rico' },
  { code3: 'GRA', code2: 'GD', name: 'Grenada' },
  { code3: 'SLC', code2: 'LC', name: 'Santa Lúcia' },
  { code3: 'BER', code2: 'BM', name: 'Bermuda' },
  { code3: 'SVG', code2: 'VC', name: 'São Vicente e Granadinas' },
  { code3: 'MTS', code2: 'MS', name: 'Montserrat' },
  { code3: 'BLZ', code2: 'BZ', name: 'Belize' },
  { code3: 'DNC', code2: 'DM', name: 'Dominica' },
  { code3: 'ARU', code2: 'AW', name: 'Aruba' },
  { code3: 'BHM', code2: 'BS', name: 'Bahamas' },
  { code3: 'CAY', code2: 'KY', name: 'Ilhas Cayman' },
  { code3: 'ITC', code2: 'TC', name: 'Ilhas Turcos e Caicos' },
  { code3: 'PAL', code2: 'ps', name: 'Palestina' },
  { code3: 'TAJ', code2: 'tj', name: 'Tajiquistão' },
  { code3: 'MSA', code2: 'my', name: 'Malásia' },
  { code3: 'CNE', code2: 'kp', name: 'Coreia do Norte' },
  { code3: 'IDN', code2: 'id', name: 'Indonésia' },
  { code3: 'KUW', code2: 'kw', name: 'Kuwait' },
  { code3: 'FIL', code2: 'ph', name: 'Filipinas' },
  { code3: 'TCM', code2: 'tm', name: 'Turquemenistão' },
  { code3: 'YEM', code2: 'ye', name: 'Iémen' },
  { code3: 'SGP', code2: 'sg', name: 'Singapura' },
  { code3: 'AFE', code2: 'af', name: 'Afeganistão' },
  { code3: 'MYA', code2: 'mm', name: 'Myanmar' },
  { code3: 'MDS', code2: 'mv', name: 'Maldivas' },
  { code3: 'CBJ', code2: 'kh', name: 'Camboja' },
  { code3: 'BAN', code2: 'bd', name: 'Bangladesh' },
  { code3: 'MGL', code2: 'mn', name: 'Mongólia' },
  { code3: 'LAO', code2: 'la', name: 'Laos' },
  { code3: 'BRU', code2: 'bn', name: 'Brunei' },
  { code3: 'BUT', code2: 'bt', name: 'Butão' },
  { code3: 'SRI', code2: 'lk', name: 'Sri Lanka' },
  { code3: 'TIM', code2: 'tl', name: 'Timor-Leste' },
  { code3: 'PAQ', code2: 'pk', name: 'Paquistão' },
  { code3: 'NCL', code2: 'nc', name: 'Nova Caledônia' },
  { code3: 'ISM', code2: 'sb', name: 'Ilhas Salomão' },
  { code3: 'FIJ', code2: 'fj', name: 'Fiji' },
  { code3: 'THT', code2: 'pf', name: 'Tahiti' }, // Taiti = Polinésia Francesa
  { code3: 'VAN', code2: 'vu', name: 'Vanuatu' },
  { code3: 'PNG', code2: 'pg', name: 'Papua-Nova Guiné' },
  { code3: 'UNK', code2: 'xx', name: 'Desconhecido' },
];
